variable "project_name" {}
variable "environment" {}
variable "aws_region" {}
variable "vpc_cidr" {}
variable "public_subnet_az1_cidr" {}
variable "public_subnet_az2_cidr" {}
variable "private_subnet_az1_cidr" {}
variable "private_subnet_az2_cidr" {}
variable "container_port" {}
variable "domain_name" {}
variable "subdomain_name" {}
variable "db_name" {}
variable "db_username" {}
variable "db_password" {}